"""
tests/test_v191_iter16_pg_events_reads.py — guard the 4 events-table
reads that bypassed the backend-aware path and silently returned empty
results in PG-only mode.

Operator report (2026-06-11):

  appsec-timescaledb  ERROR:  operator does not exist:
    timestamp with time zone >= integer
  STATEMENT:  SELECT ip, ts FROM events WHERE ts >= $1 AND ip IN ($2)

The query was generated by `dashboards/analytics.py`'s top-IPs
sparkline read. Three sibling sites (`admin/settings.py` reason-over-
time chart + dow×hour heatmap, `dashboards/service_metrics.py`
per-vhost totals) did not raise but silently returned empty data
because they hit `sqlite3.connect(_DATA_PATH)` directly instead of
going through the backend-aware `open_conn()`.

These tests anchor the four call sites by their literal SQL so a
refactor that drops the PG branch (or re-introduces a bare
`sqlite3.connect`) is caught in CI.
"""

import os
import re


_REPO = os.path.join(os.path.dirname(__file__), "..")


def _read(rel):
    return open(os.path.join(_REPO, rel), encoding="utf-8").read()


# ── analytics.py top-IPs sparkline ──────────────────────────────────────


def test_analytics_sparkline_branches_by_backend():
    """Sparkline read must dispatch through `active_backend()` so PG-only
    mode hits the to_timestamp()-wrapped query instead of the raw
    `WHERE ts >= ?` that PG rejects."""
    src = _read("dashboards/analytics.py")
    body = src[src.find("sparklines: dict ="):src.find("ban_expiry: dict")]
    assert "active_backend" in body or "_active" in body, (
        "analytics.py sparkline must check active_backend before issuing "
        "the events read (iter-16 fix family)"
    )
    assert "to_timestamp(?)" in body, (
        "PG path must wrap the WHERE bound in to_timestamp(?) — "
        "the original `WHERE ts >= ?` raises on TIMESTAMPTZ"
    )
    assert "EXTRACT(EPOCH FROM ts)" in body, (
        "PG path must project ts back to epoch via EXTRACT so the "
        "hour-bucket arithmetic below stays valid"
    )


def test_analytics_sparkline_uses_open_conn_not_raw_sqlite():
    """Must use open_conn() (backend-aware) — not a bare
    sqlite3.connect(DB_PATH) which silently returns the empty local file
    in PG-only mode."""
    src = _read("dashboards/analytics.py")
    body = src[src.find("sparklines: dict ="):src.find("ban_expiry: dict")]
    assert "open_conn()" in body, (
        "sparkline must obtain the connection via open_conn() so the PG "
        "wrapper handles cross-backend cursor + placeholder rewriting"
    )
    # Belt-and-braces: no raw `_sq3.connect(_DATA_PATH)` inside this
    # specific block (other sparkline-adjacent reads keep using SQLite
    # for SQLite-only state like abuseipdb_cache).
    assert "_sq3.connect(_DATA_PATH)" not in body, (
        "sparkline must NOT fall back to a direct local-SQLite connect — "
        "that's what the original bug was"
    )


# ── settings.py reason-over-time chart ──────────────────────────────────


def test_settings_reason_chart_branches_by_backend():
    src = _read("admin/settings.py")
    # Locate the reason-over-time SELECT — disambiguated by the GROUP BY
    # clause since iter-17 added a per-vhost slot read that ALSO uses
    # `CAST((EXTRACT(EPOCH FROM ts) - ?) / ? AS INTEGER) AS slot`.
    idx = src.find("GROUP BY reason, slot ORDER BY slot")
    assert idx != -1, (
        "settings.py reason-over-time chart must include a PG branch "
        "that projects ts → epoch via EXTRACT and groups by (reason, slot)"
    )
    body = src[max(0, idx - 1200):idx + 800]
    assert "active_backend" in body or "_active_e" in body, (
        "reason-over-time must check active_backend before choosing SQL"
    )
    assert "to_timestamp(?)" in body, (
        "PG bound must use to_timestamp() — bare WHERE ts >= ? raises"
    )
    assert "EXTRACT(EPOCH FROM ts)" in body, (
        "PG branch must project ts via EXTRACT(EPOCH FROM ts) so the "
        "downstream slot arithmetic stays valid"
    )
    # Sibling SQLite path must stay present (no regression for SQLite mode).
    assert re.search(r"FROM events WHERE ts >= \? AND ts <= \?", body), (
        "SQLite-mode branch must keep the original `ts >= ?` form so the "
        "fix does not regress sqlite-only deployments"
    )


# ── settings.py dow×hour heatmap ────────────────────────────────────────


def test_settings_dowhour_heatmap_branches_by_backend():
    src = _read("admin/settings.py")
    # PG path must use EXTRACT(DOW/HOUR) instead of SQLite's strftime.
    assert "EXTRACT(DOW  FROM ts)" in src or "EXTRACT(DOW FROM ts)" in src, (
        "heatmap PG branch must use EXTRACT(DOW FROM ts) — strftime() is "
        "SQLite-only"
    )
    assert "EXTRACT(HOUR FROM ts)" in src, (
        "heatmap PG branch must use EXTRACT(HOUR FROM ts)"
    )
    # And the SQLite path must keep the strftime form intact.
    assert "strftime('%w', ts, 'unixepoch')" in src
    assert "strftime('%H', ts, 'unixepoch')" in src


# ── service_metrics.py per-vhost totals ─────────────────────────────────


def test_service_metrics_per_vhost_branches_by_backend():
    src = _read("dashboards/service_metrics.py")
    idx = src.find("FROM events WHERE ts >= to_timestamp(?) AND ts <= to_timestamp(?) AND vhost = ?")
    assert idx != -1, (
        "service_metrics per-vhost totals must include a PG branch that "
        "wraps the ts bounds in to_timestamp()"
    )
    body = src[max(0, idx - 800):idx + 400]
    assert "active_backend" in body or "_active_v" in body, (
        "per-vhost totals must check active_backend before issuing SQL"
    )
    # Allow the aliased-import form `_open_conn_v()` too — modules sometimes
    # rename to avoid colliding with a local symbol.
    assert "open_conn" in body and "()" in body, (
        "per-vhost totals must use open_conn() — not a raw sqlite3.connect"
    )


# ── Forward-looking sweep: no new bare events reads ─────────────────────


def test_no_bare_sqlite_connect_for_events_reads_in_dashboards():
    """Catch future regressions where a new dashboard endpoint adds a
    `sqlite3.connect(_DATA_PATH)` followed by a `FROM events WHERE` —
    that pattern silently returns empty in PG-only mode.

    Whitelist files that legitimately need a SQLite-only read (e.g.
    abuseipdb_cache, config_kv mirror reads, the writer-side checks).
    """
    import subprocess
    out = subprocess.run(
        ["grep", "-rnE",
         r"sqlite3\.connect\(.*(_DATA_PATH|DB_PATH)",
         "--include=*.py", "dashboards/", "admin/"],
        cwd=_REPO, capture_output=True, text=True, check=False,
    ).stdout
    # Strip comment-only matches (e.g. iter-16 explanatory comments that
    # quote the bug pattern). Real call sites are unindented assignments.
    def _is_real_callsite(ln):
        try:
            _, _, code = ln.split(":", 2)
        except ValueError:
            return False
        return not code.lstrip().startswith("#")
    out = "\n".join(l for l in out.splitlines() if _is_real_callsite(l))
    bad = []
    for ln in out.splitlines():
        try:
            path, lineno, _ = ln.split(":", 2)
        except ValueError:
            continue
        # Read 30 lines around the hit to see whether it's followed by a
        # `FROM events` query inside the same try-block.
        try:
            buf = open(os.path.join(_REPO, path), encoding="utf-8").read().splitlines()
        except OSError:
            continue
        i = int(lineno) - 1
        window = "\n".join(buf[i:i + 30])
        if "FROM events" in window and "WHERE ts" in window:
            bad.append(ln)
    # Whitelist legitimate SQLite-only event reads (e.g. SQLite-target
    # migrations writing TO the local file, settings-import reading the
    # exported bundle). Add paths here only after confirming they are
    # backend-agnostic by design.
    whitelist = (
        # settings-import rehydrates an exported SQLite bundle into the
        # local file — by design, not the operational backend.
        "admin/settings.py:1191",
        "admin/settings.py:1192",
    )
    bad = [b for b in bad if not any(b.startswith(w) for w in whitelist)]
    assert not bad, (
        "found bare sqlite3.connect(...) followed by `FROM events WHERE ts`:\n"
        + "\n".join(bad)
        + "\n\nThese silently return empty in PG-only mode. Route through "
        "open_conn() + branch by active_backend (see iter-16 fix family)."
    )
