#!/usr/bin/env bash
#
# Seeds the public mirror with an initial PR-based merge so scorecard's
# CI-Tests, Signed-Releases, and Code-Review checks have signal to score.
#
# What this does:
#   1. On the public mirror, cut a branch `chore/scorecard-seed-pr`
#      containing ONE trivial doc edit (adds a "scorecard seed" line to
#      docs/scorecard/SEED.md).
#   2. Push the branch to origin.
#   3. Open a PR into main using `gh pr create`.
#   4. Wait for `docker.yml` CI to go green on the PR.
#   5. Merge the PR (squash). branch-protection.json sets
#      required_approving_review_count=0 for solo-dev — no approval or
#      admin bypass needed; CI green is enough.
#   6. Optionally tag + release a "no-op" v0.0.1-seed release so
#      Signed-Releases has something to score. Skipped by default (the
#      auto-release job in docker.yml will cut the first real signed
#      release on the next config.py bump).
#
# WHY: scorecard scores CI-Tests and Signed-Releases at -1 (unscored)
# until at least one PR has been merged / one release has been signed.
# One seed PR flips both to countable state; every subsequent PR then
# adds to the moving-window score.
#
# Requirements:
#   - `gh` CLI logged in with `repo` scope on tarrinho/AntiBotGW.
#   - Branch Protection may be already applied. With the shipped
#     `branch-protection.json` (reviews=0, enforce_admins=true), CI green is
#     enough to merge — no admin bypass, no approval. If you later require
#     reviews ≥ 1 (i.e. a second maintainer joins), you'll need someone
#     else to approve this seed PR.
#
# Usage:
#   ./seed-pr-flow.sh                              # default: main, no release
#   TAG_RELEASE=1 ./seed-pr-flow.sh                # also cut v0.0.1-seed
#   DRY_RUN=1 ./seed-pr-flow.sh                    # print steps, do nothing

set -euo pipefail

OWNER="${OWNER:-tarrinho}"
REPO="${REPO:-AntiBotGW}"
BASE_BRANCH="${BASE_BRANCH:-main}"
SEED_BRANCH="${SEED_BRANCH:-chore/scorecard-seed-pr}"
TAG_RELEASE="${TAG_RELEASE:-0}"
DRY_RUN="${DRY_RUN:-0}"

run() {
  if [[ "$DRY_RUN" == "1" ]]; then
    printf '[dry-run] %s\n' "$*"
  else
    "$@"
  fi
}

command -v gh >/dev/null 2>&1 || {
  echo "FATAL: gh CLI required" >&2
  exit 1
}

# Sanity: are we in a git checkout of tarrinho/AntiBotGW?
origin=$(git remote get-url origin 2>/dev/null || true)
case "$origin" in
  *"$OWNER/$REPO"*|*"$OWNER/$REPO.git"*) ;;
  *)
    echo "FATAL: origin '$origin' does not look like $OWNER/$REPO" >&2
    echo "       clone the public mirror first:" >&2
    echo "         git clone git@github.com:$OWNER/$REPO.git && cd $REPO" >&2
    echo "       and re-run this script from there." >&2
    exit 1
    ;;
esac

# 1. Prep the seed branch.
run git fetch origin "$BASE_BRANCH"
run git switch -c "$SEED_BRANCH" "origin/$BASE_BRANCH"

# 2. Trivial doc-only edit — cheapest possible PR CI can vote on.
SEED_FILE="docs/scorecard/SEED.md"
mkdir -p "$(dirname "$SEED_FILE")"
if [[ "$DRY_RUN" == "1" ]]; then
  printf '[dry-run] would write %s\n' "$SEED_FILE"
else
  cat > "$SEED_FILE" <<EOF
# Scorecard PR-flow seed

This file exists only to seed the OpenSSF Scorecard \`CI-Tests\` and
\`Code-Review\` checks — both score \`-1\` (unscored) until the repository
has at least one merged PR. Merging this file's introduction gives them
signal to start scoring.

Subsequent PRs will overwrite / delete this file freely; do not treat it
as load-bearing.

Seeded: $(date -u +%FT%TZ)
EOF
fi
run git add "$SEED_FILE"
run git -c commit.gpgsign=false commit -m "chore: seed PR flow for scorecard CI-Tests + Code-Review"
run git push -u origin "$SEED_BRANCH"

# 3. Open the PR.
PR_BODY='## Scorecard seed

Seeds the OpenSSF Scorecard `CI-Tests`, `Code-Review`, and `Signed-Releases`
checks by creating the repository'"'"'s first PR-based merge. All three
signal `-1` (unscored) until a PR has actually flowed through `main`.

Trivial doc addition — `docs/scorecard/SEED.md` — no runtime change.

Auto-generated by `docs/scorecard/seed-pr-flow.sh`.
'
if [[ "$DRY_RUN" == "1" ]]; then
  echo "[dry-run] gh pr create --base $BASE_BRANCH --head $SEED_BRANCH ..."
  PR_URL="(dry-run)"
else
  PR_URL=$(gh pr create \
    --base "$BASE_BRANCH" \
    --head "$SEED_BRANCH" \
    --title "chore: seed PR-flow for scorecard CI-Tests + Code-Review" \
    --body "$PR_BODY")
fi
echo "→ PR: $PR_URL"

# 4. Wait for CI to pass.
if [[ "$DRY_RUN" != "1" ]]; then
  echo "→ waiting for docker.yml checks (may take 10-15 min)..."
  gh pr checks "$PR_URL" --watch --interval 30 --fail-fast
fi

# 5. Merge (CI-green is enough — reviews=0 for solo-dev; no admin bypass so
#    status checks stay enforced).
run gh pr merge "$PR_URL" --squash --delete-branch

# 6. Optional seed release.
if [[ "$TAG_RELEASE" == "1" ]]; then
  echo "→ cutting seed release v0.0.1-seed (cosign-signed via docker.yml)"
  run git switch "$BASE_BRANCH"
  run git pull --ff-only origin "$BASE_BRANCH"
  run git tag -a v0.0.1-seed -m "scorecard seed release"
  run git push origin v0.0.1-seed
  # docker.yml auto-release job picks up the tag push and cuts the GitHub Release.
fi

echo
echo "✔ done. Next scorecard scan should:"
echo "    CI-Tests        -1 → 10 (PR merged with green CI)"
echo "    Code-Review      0 →  1 (1/30 changesets — climbs as more PRs merge)"
[[ "$TAG_RELEASE" == "1" ]] && \
  echo "    Signed-Releases -1 → 10 (cosign-signed release cut)"
